### ISSUE TITLE
Some in line LaTeX not showing up in Markdown Cell

### ISSUE THREAD

**Issue by sbs0034** [andrew-t/quaver#30] opened 2015-12-08 20:12 UTC
LaTeX such as $\oint$ is showing up as regular Markdown and not LaTeX

**Comment by andrew-t** [comment] 2015-12-09 08:12
I can't reproduce this. \oint works on my Nexus 5X.
![screen shot 2015-12-09 at 08 10 21](https://cloud.githubusercontent.com/assets/3949426/11679908/7a66ceb0-9e4c-11e5-9185-eebfd6090dfa.png)

Any chance of a longer snippet that definitely fails?

**Comment by sbs0034** [comment] 2015-12-10 02:31
When I get home, I will post a screenshot of the preview, and i will also upload the markdown file.

**Comment by sbs0034** [comment] 2015-12-10 03:11
---

## **Here are the screenshots from Quaver running on my HTC Nexus 9**...

![quaver screenshot 1](https://cloud.githubusercontent.com/assets/10619695/11705808/9e547234-9eb8-11e5-8319-07865a14d7c3.png)
![quaver screenshot 2](https://cloud.githubusercontent.com/assets/10619695/11705809/a404244a-9eb8-11e5-9459-e5f40c5d0121.png)

---

## **Here is the qvnote file from Quiver on the mac** (same file on Android)

[Things to study.qvnote.zip](https://github.com/andrew-t/quaver/files/57600/Things.to.study.qvnote.zip)

---

## *\* Quiver Preview exported to PDF**

[Things to study Quiver Mac.pdf](https://github.com/andrew-t/quaver/files/57602/Things.to.study.Quiver.Mac.pdf)

---

## **Quiver note txt file**

[Things to study.txt](https://github.com/andrew-t/quaver/files/57603/Things.to.study.txt)

**Comment by andrew-t** [comment] 2015-12-10 07:30
Thanks, that's really useful. I’ll have a look into it when I get chance.

**Comment by andrew-t** [comment] 2015-12-10 11:47
OK, the issue appears to be caused by characters like `_` which have
special meanings in both Markdown and LaTeX. Quiver correctly ignores them
while parsing Markdown, but Quaver parses the Markdown first, breaking the
LaTeX.

There are a couple of ways I could fix this butI can't think of an
especially easy one, so it'll probably be a few days if that's OK?

**Comment by sbs0034** [comment] 2015-12-10 15:14
Yes that’s great, I could try and help, though I mostly develop Python applications so I don’t know how useful I would be.

**Comment by andrew-t** [comment] 2015-12-10 15:36
It’s OK, I know what I need to do — I just need to find a bit of time. To be honest the most useful thing you could do would be to pick up some Christmas shopping for me.

**Comment by andrew-t** [comment] 2015-12-12 15:01
Right — this seems to be fixed in the latest version.

**Closed as completed by andrew-t** 2015-12-12 15:01 UTC
Labels: bug
